# Generated by Django 6.0.2 on 2026-02-25 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_loginattempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=255)),
                ('pallet_id', models.CharField(max_length=100)),
                ('item_count', models.IntegerField()),
                ('item_ids', models.TextField(blank=True, default='')),
                ('deleted_by', models.CharField(max_length=255)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-deleted_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='loginattempt',
            new_name='inventory_l_ip_addr_8e41f7_idx',
            old_name='inventory_l_ip_addr_idx',
        ),
    ]
