# Generated by Django 6.0.2 on 2026-02-26 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_deletionlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
